name: coromandel_mobile
description: Mobile app for Coromandel restaurant

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^0.0.13
  http: ^0.12.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  json_annotation: ^0.2.3

dev_dependencies:
#  build_runner: ^0.8.0
#  json_serializable: ^0.5.0
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #pictures
    - assets/images/default_food_image.jpg
    - assets/images/splash_logo.png
    - assets/images/carousel_gallery_1.jpg
    - assets/images/carousel_gallery_2.jpg
    - assets/images/carousel_gallery_3.jpg
    - assets/images/carousel_gallery_4.jpg
    - assets/images/carousel_gallery_5.jpg

  #icons
    - assets/icons/gluten_free_icon.png
    - assets/icons/vegan_icon.png
    - assets/icons/coupon_icon.png
    - assets/icons/cart_empty.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
